name: al_sakr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # أضيفت لحل مشكلة الترجمة
    sdk: flutter
  
  # مكتبات أضيفت بناءً على أخطاء الكود
  pocketbase: ^0.23.0
  flutter_local_notifications: ^17.0.0
  badges: ^3.1.2
  flutter_background_service: ^5.0.10
  
  # المكتبات الأصلية الخاصة بك
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  share_plus: ^7.2.1
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  excel: ^4.0.0
  image_picker: ^1.0.4
  archive: ^3.6.1
  cupertino_icons: ^1.0.8
  sentry_flutter: ^9.9.1
  msix: ^3.16.1
  firebase_core: ^3.0.0
  firebase_database: ^11.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  sqlite3_flutter_libs: ^0.5.20
  http: ^1.1.0
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  open_file: ^3.5.10
  printing: ^5.11.0
  docx_template: ^0.4.0
  syncfusion_flutter_pdf: ^24.1.41
  syncfusion_flutter_core: ^24.1.41
  arabic_reshaper: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    icon_size: 48
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png
    - assets/fonts/Cairo-Regular.ttf
    - assets/fonts/Cairo-Bold.ttf
    - assets/fonts/Traditional-Arabic.ttf
    - assets/fonts/Tinos-Regular.ttf
    - assets/fonts/Tinos-Bold.ttf
    - assets/fonts/Amiri-Regular.ttf
    - assets/fonts/Amiri-Bold.ttf
    - assets/delivery_template.docx

msix_config:
  display_name: AL SAKR
  publisher_display_name: Abdallah Ashour
  identity_name: com.alsakr.accounting
  msix_version: 1.0.0.0
  logo_path: assets/icon.png
  create_desktop_shortcut: true
